# Generated by Django 2.1.4 on 2019-01-10 21:53

import django.core.validators
from django.db import migrations, models
import rest.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20181219_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=50)),
                ('vcpu', models.IntegerField(verbose_name='vCPU')),
                ('memory_gb', models.FloatField(verbose_name='Memory (GB)')),
                ('price_per_hour', models.FloatField(verbose_name='Price per hour (USD)')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumerics, undescore, hypens characters are allowed.'), rest.validators.validate_course_name], verbose_name='Course Title'),
        ),
        migrations.AlterUniqueTogether(
            name='vmsize',
            unique_together={('name', 'region')},
        ),
    ]
