# Generated by Django 2.1.4 on 2019-01-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20190110_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmsize',
            name='price_per_hour',
        ),
    ]
