# Generated by Django 2.1.4 on 2019-01-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_remove_vmsize_price_per_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vmsize',
            old_name='region',
            new_name='cloud_region',
        ),
        migrations.AlterUniqueTogether(
            name='vmsize',
            unique_together={('name', 'cloud_region')},
        ),
    ]
