# Generated by Django 2.1.4 on 2019-01-11 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20190110_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vmsize',
            old_name='cloud_region',
            new_name='location',
        ),
        migrations.AlterUniqueTogether(
            name='vmsize',
            unique_together={('name', 'location')},
        ),
    ]
