# Generated by Django 2.1.4 on 2019-01-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20190110_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='cloud_region',
            field=models.CharField(blank=True, choices=[('westus', 'US West'), ('eastus', 'US East'), ('westeurope', 'Europe West')], max_length=100, null=True),
        ),
    ]
