# Generated by Django 2.1.4 on 2019-01-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20190110_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='location',
            field=models.CharField(default=-1, max_length=50, verbose_name='Cloud Region'),
            preserve_default=False,
        ),
    ]
