# Generated by Django 2.1.4 on 2019-01-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_pod_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='image_src',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Azure Image'),
        ),
        migrations.AddField(
            model_name='pod',
            name='vm_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Azure VM Size'),
        ),
    ]
