# Generated by Django 2.1.4 on 2019-01-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20190116_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='image_src',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Azure Image'),
        ),
    ]
