# Generated by Django 2.1.4 on 2019-01-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20190116_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='allow_internet_outbound',
            field=models.BooleanField(default=False, verbose_name='Allow Outbound Internet Access'),
        ),
    ]
